name: location_android_easy
version: 1.0.1+1
homepage: https://github.com/07ami/location_android_easy.git
description: A cross platform plugin for obtaining location information of android platform
environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.bo.location_android_easy
        pluginClass: LocationAndroidEasyPlugin
